MonoControl:
    Options: --jit

# Uncommented these options as needed.
# To learn more about these config options, check out the OS & Device Configuration documentation.
# http://developer.wildernesslabs.co/Meadow/Meadow.OS/Configuration/OS_Device_Configuration/

# Device:
#     # Name of the device on the network.
#     Name: MeadowF7V2_ConfigSample
#
#     # Uncomment if SD card hardware present on this hardware (e.g., Core-Compute module with SD add-on)? Optional; default value is `false`.
#     SdStorageSupported: true
# # Control how the ESP coprocessor will start and operate.
Coprocessor:
    AutomaticallyStartNetwork: true
    AutomaticallyReconnect: true
    MaximumRetryCount: 7

# Network configuration.
Network:
  Interfaces: 
      - Name: WiFi
        UseDHCP: false
        IPAddress: 192.168.1.60
        NetMask: 255.255.255.0
        Gateway: 192.168.1.1
#
#     # Which interface should be used?
DefaultInterface: WiFi
#
#     # Automatically attempt to get the time at startup?
GetNetworkTimeAtStartup: true
#
#     # Time synchronization period in seconds.
NtpRefreshPeriodSeconds: 600
#
#     # Name of the NTP servers.
NtpServers:
 - 0.pool.ntp.org
 - 1.pool.ntp.org
 - 2.pool.ntp.org
 - 3.pool.ntp.org
#
#     # IP addresses of the DNS servers.
DnsServers:
 - 1.1.1.1
 - 8.8.8.8